# Generated by Django 3.2.7 on 2021-10-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_terms',
            field=models.CharField(choices=[('30-70%', '30-70%'), ('50-50%', '50-50%'), ('Cash On Delivery', 'Cash On Delivery'), ('Credit', 'Credit')], max_length=50),
        ),
    ]
