# Generated by Django 3.2.7 on 2021-10-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contract_contract_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(),
        ),
    ]
