# Generated by Django 3.2.7 on 2021-10-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211024_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
