# Generated by Django 3.2.8 on 2021-10-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_amount',
            field=models.FloatField(default=450),
            preserve_default=False,
        ),
    ]
