# Generated by Django 3.2.8 on 2021-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transaction_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=234),
            preserve_default=False,
        ),
    ]
