# Generated by Django 3.2.8 on 2021-10-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211013_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='transactions_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='Enter your email address', max_length=150),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField()),
                ('invoice_number', models.FloatField()),
                ('product_name', models.CharField(max_length=30)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
