# Generated by Django 3.2.8 on 2021-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211027_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(),
        ),
    ]
