# Generated by Django 3.2.7 on 2021-10-24 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_acuser_pauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Part Payment', 'Part Payment')], max_length=50)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_due', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('supplier', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
