# Generated by Django 3.2.8 on 2021-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_rename_swift_code_accountant_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='invoice_number',
            field=models.CharField(default=8751263571543675, max_length=50),
            preserve_default=False,
        ),
    ]
