# Generated by Django 3.2.7 on 2021-10-22 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_auto_20211022_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='balance_due',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 22, 11, 6, 34, 586256)),
        ),
    ]
