# Generated by Django 3.2.7 on 2021-10-23 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0004_alter_accountant_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='bal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='balance_due',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 23, 9, 41, 29, 234505)),
        ),
    ]
