# Generated by Django 3.2.7 on 2021-10-23 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_auto_20211023_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountant',
            name='bal',
        ),
        migrations.AlterField(
            model_name='accountant',
            name='balance_due',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 23, 9, 42, 22, 453103)),
        ),
    ]
